[metadata]
name = aa-memberaudit
version = attr: memberaudit.__version__
author = Erik Kalkoken
author_email = kalkoken87@gmail.com
description = An Alliance Auth app that provides full access to Eve characters and related reports for auditing, vetting and monitoring.
long_description = file: README.md
long_description_content_type = text/markdown
url = https://gitlab.com/ErikKalkoken/aa-memberaudit
keywords = allianceauth
license = MIT
classifiers =
    Environment :: Web Environment
    Framework :: Django
    Framework :: Django :: 4.0
    Intended Audience :: Developers
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent
    Programming Language :: Python
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Topic :: Internet :: WWW/HTTP
    Topic :: Internet :: WWW/HTTP :: Dynamic Content

[options]
include_package_data = True
packages = find_namespace:
python_requires = ~=3.8
install_requires =
    allianceauth>=3
    django-eveuniverse>=0.19
    allianceauth-app-utils>=1.16.1
    humanize
    dj-datatables-view
    bleach
    unidecode

[flake8]
exclude = .git, *migrations*, .tox, dist, htmlcov
max-line-length = 88
select = C,E,F,W,B,B950
ignore = E203, E231, E501, W503, W291, W293

[isort]
profile = black
multi_line_output = 3
sections=FUTURE,STDLIB,THIRDPARTY,DJANGO,ALLIANCEAUTH,FIRSTPARTY,LOCALFOLDER
known_allianceauth=allianceauth,app_utils
known_django=django,django_webtest,esi,eveuniverse
