[flake8]
exclude = .git, *migrations*, .tox, dist, htmlcov
max-line-length = 88
select = C,E,F,W,B,B950
ignore = E501, W503

[tox]
envlist = {py38, py39, py310, py311}-django{40}, docs, pylint

[testenv]
setenv =
    DJANGO_SETTINGS_MODULE = testauth.settings

deps=
    django-webtest
    requests-mock
    coverage
    factory_boy

commands=
    python -V
    coverage run runtests.py memberaudit -v=2 --noinput --exclude-tag=breaks_with_tox
    coverage xml
    coverage report -m

[testenv:docs]
description = invoke sphinx-build to build the HTML docs
skip_install = True
deps = -r{toxinidir}/docs/requirements.txt
install_command = python -I -m pip install {opts} {packages}
commands =
    sphinx-build -d "{toxworkdir}/docs_doctree" docs "{toxworkdir}/docs_out" --color -W -bhtml {posargs}


[testenv:pylint]
deps=
    pylint
    pylint-django
    django-webtest
    requests-mock
    coverage
    tblib
    Redis

commands=
    pylint --load-plugins pylint_django memberaudit
