"""Render notifications for users."""

from enum import Enum
from typing import Tuple

from eveuniverse.models import EveEntity


class NotificationType(str, Enum):
    """A notification type."""

    ACCEPTED_ALLY = "AcceptedAlly"
    ACCEPTED_SURRENDER = "AcceptedSurrender"
    AGENT_RETIRED_TRIGRAVIAN = "AgentRetiredTrigravian"
    ALL_ANCHORING_MSG = "AllAnchoringMsg"
    ALL_MAINTENANCE_BILL_MSG = "AllMaintenanceBillMsg"
    ALL_STRUC_INVULNERABLE_MSG = "AllStrucInvulnerableMsg"
    ALL_STRUCT_VULNERABLE_MSG = "AllStructVulnerableMsg"
    ALL_WAR_CORP_JOINED_ALLIANCE_MSG = "AllWarCorpJoinedAllianceMsg"
    ALL_WAR_DECLARED_MSG = "AllWarDeclaredMsg"
    ALL_WAR_INVALIDATED_MSG = "AllWarInvalidatedMsg"
    ALL_WAR_RETRACTED_MSG = "AllWarRetractedMsg"
    ALL_WAR_SURRENDER_MSG = "AllWarSurrenderMsg"
    ALLIANCE_CAPITAL_CHANGED = "AllianceCapitalChanged"
    ALLIANCE_WAR_DECLARED_V_2 = "AllianceWarDeclaredV2"
    ALLY_CONTRACT_CANCELLED = "AllyContractCancelled"
    ALLY_JOINED_WAR_AGGRESSOR_MSG = "AllyJoinedWarAggressorMsg"
    ALLY_JOINED_WAR_ALLY_MSG = "AllyJoinedWarAllyMsg"
    ALLY_JOINED_WAR_DEFENDER_MSG = "AllyJoinedWarDefenderMsg"
    BATTLE_PUNISH_FRIENDLY_FIRE = "BattlePunishFriendlyFire"
    BILL_OUT_OF_MONEY_MSG = "BillOutOfMoneyMsg"
    BILL_PAID_CORP_ALL_MSG = "BillPaidCorpAllMsg"
    BOUNTY_CLAIM_MSG = "BountyClaimMsg"
    BOUNTY_ESS_SHARED = "BountyESSShared"
    BOUNTY_ESS_TAKEN = "BountyESSTaken"
    BOUNTY_PLACED_ALLIANCE = "BountyPlacedAlliance"
    BOUNTY_PLACED_CHAR = "BountyPlacedChar"
    BOUNTY_PLACED_CORP = "BountyPlacedCorp"
    BOUNTY_YOUR_BOUNTY_CLAIMED = "BountyYourBountyClaimed"
    BUDDY_CONNECT_CONTACT_ADD = "BuddyConnectContactAdd"
    CHAR_APP_ACCEPT_MSG = "CharAppAcceptMsg"
    CHAR_APP_REJECT_MSG = "CharAppRejectMsg"
    CHAR_APP_WITHDRAW_MSG = "CharAppWithdrawMsg"
    CHAR_LEFT_CORP_MSG = "CharLeftCorpMsg"
    CHAR_MEDAL_MSG = "CharMedalMsg"
    CHAR_TERMINATION_MSG = "CharTerminationMsg"
    CLONE_ACTIVATION_MSG = "CloneActivationMsg"
    CLONE_ACTIVATION_MSG_2 = "CloneActivationMsg2"
    CLONE_MOVED_MSG = "CloneMovedMsg"
    CLONE_REVOKED_MSG_1 = "CloneRevokedMsg1"
    CLONE_REVOKED_MSG_2 = "CloneRevokedMsg2"
    COMBAT_OPERATION_FINISHED = "CombatOperationFinished"
    CONTACT_ADD = "ContactAdd"
    CONTACT_EDIT = "ContactEdit"
    CONTAINER_PASSWORD_MSG = "ContainerPasswordMsg"
    CONTRACT_REGION_CHANGED_TO_POCHVEN = "ContractRegionChangedToPochven"
    CORP_ALL_BILL_MSG = "CorpAllBillMsg"
    CORP_APP_ACCEPT_MSG = "CorpAppAcceptMsg"
    CORP_APP_INVITED_MSG = "CorpAppInvitedMsg"
    CORP_APP_NEW_MSG = "CorpAppNewMsg"
    CORP_APP_REJECT_CUSTOM_MSG = "CorpAppRejectCustomMsg"
    CORP_APP_REJECT_MSG = "CorpAppRejectMsg"
    CORP_BECAME_WAR_ELIGIBLE = "CorpBecameWarEligible"
    CORP_DIVIDEND_MSG = "CorpDividendMsg"
    CORP_FRIENDLY_FIRE_DISABLE_TIMER_COMPLETED = "CorpFriendlyFireDisableTimerCompleted"
    CORP_FRIENDLY_FIRE_DISABLE_TIMER_STARTED = "CorpFriendlyFireDisableTimerStarted"
    CORP_FRIENDLY_FIRE_ENABLE_TIMER_COMPLETED = "CorpFriendlyFireEnableTimerCompleted"
    CORP_FRIENDLY_FIRE_ENABLE_TIMER_STARTED = "CorpFriendlyFireEnableTimerStarted"
    CORP_KICKED = "CorpKicked"
    CORP_LIQUIDATION_MSG = "CorpLiquidationMsg"
    CORP_NEW_CEO_MSG = "CorpNewCEOMsg"
    CORP_NEWS_MSG = "CorpNewsMsg"
    CORP_NO_LONGER_WAR_ELIGIBLE = "CorpNoLongerWarEligible"
    CORP_OFFICE_EXPIRATION_MSG = "CorpOfficeExpirationMsg"
    CORP_STRUCT_LOST_MSG = "CorpStructLostMsg"
    CORP_TAX_CHANGE_MSG = "CorpTaxChangeMsg"
    CORP_VOTE_CEO_REVOKED_MSG = "CorpVoteCEORevokedMsg"
    CORP_VOTE_MSG = "CorpVoteMsg"
    CORP_WAR_DECLARED_MSG = "CorpWarDeclaredMsg"
    CORP_WAR_DECLARED_V_2 = "CorpWarDeclaredV2"
    CORP_WAR_FIGHTING_LEGAL_MSG = "CorpWarFightingLegalMsg"
    CORP_WAR_INVALIDATED_MSG = "CorpWarInvalidatedMsg"
    CORP_WAR_RETRACTED_MSG = "CorpWarRetractedMsg"
    CORP_WAR_SURRENDER_MSG = "CorpWarSurrenderMsg"
    CORPORATION_GOAL_CLOSED = "CorporationGoalClosed"
    CORPORATION_GOAL_COMPLETED = "CorporationGoalCompleted"
    CORPORATION_GOAL_CREATED = "CorporationGoalCreated"
    CUSTOMS_MSG = "CustomsMsg"
    DECLARE_WAR = "DeclareWar"
    DISTRICT_ATTACKED = "DistrictAttacked"
    DUST_APP_ACCEPTED_MSG = "DustAppAcceptedMsg"
    ESS_MAIN_BANK_LINK = "ESSMainBankLink"
    ENTOSIS_CAPTURE_STARTED = "EntosisCaptureStarted"
    EXPERT_SYSTEM_EXPIRED = "ExpertSystemExpired"
    EXPERT_SYSTEM_EXPIRY_IMMINENT = "ExpertSystemExpiryImminent"
    FW_ALLIANCE_KICK_MSG = "FWAllianceKickMsg"
    FW_ALLIANCE_WARNING_MSG = "FWAllianceWarningMsg"
    FW_CHAR_KICK_MSG = "FWCharKickMsg"
    FW_CHAR_RANK_GAIN_MSG = "FWCharRankGainMsg"
    FW_CHAR_RANK_LOSS_MSG = "FWCharRankLossMsg"
    FW_CHAR_WARNING_MSG = "FWCharWarningMsg"
    FW_CORP_JOIN_MSG = "FWCorpJoinMsg"
    FW_CORP_KICK_MSG = "FWCorpKickMsg"
    FW_CORP_LEAVE_MSG = "FWCorpLeaveMsg"
    FW_CORP_WARNING_MSG = "FWCorpWarningMsg"
    FAC_WAR_CORP_JOIN_REQUEST_MSG = "FacWarCorpJoinRequestMsg"
    FAC_WAR_CORP_JOIN_WITHDRAW_MSG = "FacWarCorpJoinWithdrawMsg"
    FAC_WAR_CORP_LEAVE_REQUEST_MSG = "FacWarCorpLeaveRequestMsg"
    FAC_WAR_CORP_LEAVE_WITHDRAW_MSG = "FacWarCorpLeaveWithdrawMsg"
    FAC_WAR_LP_DISQUALIFIED_EVENT = "FacWarLPDisqualifiedEvent"
    FAC_WAR_LP_DISQUALIFIED_KILL = "FacWarLPDisqualifiedKill"
    FAC_WAR_LP_PAYOUT_EVENT = "FacWarLPPayoutEvent"
    FAC_WAR_LP_PAYOUT_KILL = "FacWarLPPayoutKill"
    GAME_TIME_ADDED = "GameTimeAdded"
    GAME_TIME_RECEIVED = "GameTimeReceived"
    GAME_TIME_SENT = "GameTimeSent"
    GIFT_RECEIVED = "GiftReceived"
    IHUB_DESTROYED_BY_BILL_FAILURE = "IHubDestroyedByBillFailure"
    INCURSION_COMPLETED_MSG = "IncursionCompletedMsg"
    INDUSTRY_OPERATION_FINISHED = "IndustryOperationFinished"
    INDUSTRY_TEAM_AUCTION_LOST = "IndustryTeamAuctionLost"
    INDUSTRY_TEAM_AUCTION_WON = "IndustryTeamAuctionWon"
    INFRASTRUCTURE_HUB_BILL_ABOUT_TO_EXPIRE = "InfrastructureHubBillAboutToExpire"
    INSURANCE_EXPIRATION_MSG = "InsuranceExpirationMsg"
    INSURANCE_FIRST_SHIP_MSG = "InsuranceFirstShipMsg"
    INSURANCE_INVALIDATED_MSG = "InsuranceInvalidatedMsg"
    INSURANCE_ISSUED_MSG = "InsuranceIssuedMsg"
    INSURANCE_PAYOUT_MSG = "InsurancePayoutMsg"
    INVASION_COMPLETED_MSG = "InvasionCompletedMsg"
    INVASION_SYSTEM_LOGIN = "InvasionSystemLogin"
    INVASION_SYSTEM_START = "InvasionSystemStart"
    JUMP_CLONE_DELETED_MSG_1 = "JumpCloneDeletedMsg1"
    JUMP_CLONE_DELETED_MSG_2 = "JumpCloneDeletedMsg2"
    KILL_REPORT_FINAL_BLOW = "KillReportFinalBlow"
    KILL_REPORT_VICTIM = "KillReportVictim"
    KILL_RIGHT_AVAILABLE = "KillRightAvailable"
    KILL_RIGHT_AVAILABLE_OPEN = "KillRightAvailableOpen"
    KILL_RIGHT_EARNED = "KillRightEarned"
    KILL_RIGHT_UNAVAILABLE = "KillRightUnavailable"
    KILL_RIGHT_UNAVAILABLE_OPEN = "KillRightUnavailableOpen"
    KILL_RIGHT_USED = "KillRightUsed"
    LOCATE_CHAR_MSG = "LocateCharMsg"
    MADE_WAR_MUTUAL = "MadeWarMutual"
    MERC_OFFER_RETRACTED_MSG = "MercOfferRetractedMsg"
    MERC_OFFERED_NEGOTIATION_MSG = "MercOfferedNegotiationMsg"
    MISSION_CANCELED_TRIGLAVIAN = "MissionCanceledTriglavian"
    MISSION_OFFER_EXPIRATION_MSG = "MissionOfferExpirationMsg"
    MISSION_TIMEOUT_MSG = "MissionTimeoutMsg"
    MOONMINING_AUTOMATIC_FRACTURE = "MoonminingAutomaticFracture"
    MOONMINING_EXTRACTION_CANCELLED = "MoonminingExtractionCancelled"
    MOONMINING_EXTRACTION_FINISHED = "MoonminingExtractionFinished"
    MOONMINING_EXTRACTION_STARTED = "MoonminingExtractionStarted"
    MOONMINING_LASER_FIRED = "MoonminingLaserFired"
    MUTUAL_WAR_EXPIRED = "MutualWarExpired"
    MUTUAL_WAR_INVITE_ACCEPTED = "MutualWarInviteAccepted"
    MUTUAL_WAR_INVITE_REJECTED = "MutualWarInviteRejected"
    MUTUAL_WAR_INVITE_SENT = "MutualWarInviteSent"
    NPC_STANDINGS_GAINED = "NPCStandingsGained"
    NPC_STANDINGS_LOST = "NPCStandingsLost"
    OFFER_TO_ALLY_RETRACTED = "OfferToAllyRetracted"
    OFFERED_SURRENDER = "OfferedSurrender"
    OFFERED_TO_ALLY = "OfferedToAlly"
    OFFICE_LEASE_CANCELED_INSUFFICIENT_STANDINGS = (
        "OfficeLeaseCanceledInsufficientStandings"
    )
    OLD_LSC_MESSAGES = "OldLscMessages"
    OPERATION_FINISHED = "OperationFinished"
    ORBITAL_ATTACKED = "OrbitalAttacked"
    ORBITAL_REINFORCED = "OrbitalReinforced"
    OWNERSHIP_TRANSFERRED = "OwnershipTransferred"
    RAFFLE_CREATED = "RaffleCreated"
    RAFFLE_EXPIRED = "RaffleExpired"
    RAFFLE_FINISHED = "RaffleFinished"
    REIMBURSEMENT_MSG = "ReimbursementMsg"
    RESEARCH_MISSION_AVAILABLE_MSG = "ResearchMissionAvailableMsg"
    RETRACTS_WAR = "RetractsWar"
    SEASONAL_CHALLENGE_COMPLETED = "SeasonalChallengeCompleted"
    SOV_ALL_CLAIM_AQUIRED_MSG = "SovAllClaimAquiredMsg"
    SOV_ALL_CLAIM_LOST_MSG = "SovAllClaimLostMsg"
    SOV_COMMAND_NODE_EVENT_STARTED = "SovCommandNodeEventStarted"
    SOV_CORP_BILL_LATE_MSG = "SovCorpBillLateMsg"
    SOV_CORP_CLAIM_FAIL_MSG = "SovCorpClaimFailMsg"
    SOV_DISRUPTOR_MSG = "SovDisruptorMsg"
    SOV_STATION_ENTERED_FREEPORT = "SovStationEnteredFreeport"
    SOV_STRUCTURE_DESTROYED = "SovStructureDestroyed"
    SOV_STRUCTURE_REINFORCED = "SovStructureReinforced"
    SOV_STRUCTURE_SELF_DESTRUCT_CANCEL = "SovStructureSelfDestructCancel"
    SOV_STRUCTURE_SELF_DESTRUCT_FINISHED = "SovStructureSelfDestructFinished"
    SOV_STRUCTURE_SELF_DESTRUCT_REQUESTED = "SovStructureSelfDestructRequested"
    SOVEREIGNTY_IH_DAMAGE_MSG = "SovereigntyIHDamageMsg"
    SOVEREIGNTY_SBU_DAMAGE_MSG = "SovereigntySBUDamageMsg"
    SOVEREIGNTY_TCU_DAMAGE_MSG = "SovereigntyTCUDamageMsg"
    STATION_AGGRESSION_MSG_1 = "StationAggressionMsg1"
    STATION_AGGRESSION_MSG_2 = "StationAggressionMsg2"
    STATION_CONQUER_MSG = "StationConquerMsg"
    STATION_SERVICE_DISABLED = "StationServiceDisabled"
    STATION_SERVICE_ENABLED = "StationServiceEnabled"
    STATION_STATE_CHANGE_MSG = "StationStateChangeMsg"
    STORY_LINE_MISSION_AVAILABLE_MSG = "StoryLineMissionAvailableMsg"
    STRUCTURE_ANCHORING = "StructureAnchoring"
    STRUCTURE_COURIER_CONTRACT_CHANGED = "StructureCourierContractChanged"
    STRUCTURE_DESTROYED = "StructureDestroyed"
    STRUCTURE_FUEL_ALERT = "StructureFuelAlert"
    STRUCTURE_IMPENDING_ABANDONMENT_ASSETS_AT_RISK = (
        "StructureImpendingAbandonmentAssetsAtRisk"
    )
    STRUCTURE_ITEMS_DELIVERED = "StructureItemsDelivered"
    STRUCTURE_ITEMS_MOVED_TO_SAFETY = "StructureItemsMovedToSafety"
    STRUCTURE_LOST_ARMOR = "StructureLostArmor"
    STRUCTURE_LOST_SHIELDS = "StructureLostShields"
    STRUCTURE_ONLINE = "StructureOnline"
    STRUCTURE_PAINT_PURCHASED = "StructurePaintPurchased"
    STRUCTURE_SERVICES_OFFLINE = "StructureServicesOffline"
    STRUCTURE_UNANCHORING = "StructureUnanchoring"
    STRUCTURE_UNDER_ATTACK = "StructureUnderAttack"
    STRUCTURE_WENT_HIGH_POWER = "StructureWentHighPower"
    STRUCTURE_WENT_LOW_POWER = "StructureWentLowPower"
    STRUCTURES_JOBS_CANCELLED = "StructuresJobsCancelled"
    STRUCTURES_JOBS_PAUSED = "StructuresJobsPaused"
    STRUCTURES_REINFORCEMENT_CHANGED = "StructuresReinforcementChanged"
    TOWER_ALERT_MSG = "TowerAlertMsg"
    TOWER_RESOURCE_ALERT_MSG = "TowerResourceAlertMsg"
    TRANSACTION_REVERSAL_MSG = "TransactionReversalMsg"
    TUTORIAL_MSG = "TutorialMsg"
    WAR_ADOPTED = "WarAdopted"
    WAR_ALLY_INHERITED = "WarAllyInherited"
    WAR_ALLY_OFFER_DECLINED_MSG = "WarAllyOfferDeclinedMsg"
    WAR_CONCORD_INVALIDATES = "WarConcordInvalidates"
    WAR_DECLARED = "WarDeclared"
    WAR_ENDED_HQ_SECURITY_DROP = "WarEndedHqSecurityDrop"
    WAR_HQ_REMOVED_FROM_SPACE = "WarHQRemovedFromSpace"
    WAR_INHERITED = "WarInherited"
    WAR_INVALID = "WarInvalid"
    WAR_RETRACTED = "WarRetracted"
    WAR_RETRACTED_BY_CONCORD = "WarRetractedByConcord"
    WAR_SURRENDER_DECLINED_MSG = "WarSurrenderDeclinedMsg"
    WAR_SURRENDER_OFFER_MSG = "WarSurrenderOfferMsg"


def render_content(notification_type: str, details: dict) -> Tuple[str, str]:
    """Render content of a notification.

    Returns content as plain text title and markdown text.
    """

    notif_type = NotificationType(notification_type)

    if notif_type == NotificationType.CORP_APP_NEW_MSG:
        character = EveEntity.objects.get_or_create_esi(details["charID"])
        title = f"Corporation application from {character}"
        text = (
            f"{character} has submitted a corporation application "
            "with the following text:\n"
            f'{details["applicationText"]}'
        )

    else:
        raise NotImplementedError(notif_type)

    return title, text
