# Generated by Django 4.0.10 on 2023-09-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memberaudit", "0012_add_corporation_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterupdatestatus",
            name="has_token_error",
            field=models.BooleanField(
                default=False, help_text="Whether this section has a token error."
            ),
        ),
    ]
