# Generated by Django 4.0.10 on 2023-09-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memberaudit", "0013_alter_characterrole_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterrole",
            name="location",
            field=models.CharField(
                choices=[
                    ("BS", "base"),
                    ("HQ", "headquarters"),
                    ("OT", "other"),
                    ("UV", "universal"),
                ],
                help_text="Location where this role is applicable.",
                max_length=2,
            ),
        ),
    ]
