# Generated by Django 4.0.10 on 2023-11-14 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("memberaudit", "0015_add_ship_item_id"),
        ("memberaudit", "0016_delete_characterlocation"),
        ("memberaudit", "0017_recreate_characterlocation"),
    ]

    dependencies = [
        ("memberaudit", "0014_fix_default_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactership",
            name="item_id",
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="CharacterLocation",
        ),
        migrations.CreateModel(
            name="CharacterLocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location",
                        to="memberaudit.character",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="memberaudit.location",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
