# Generated by Django 4.0.10 on 2023-10-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memberaudit", "0014_alter_characterupdatestatus_section_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characternotification",
            name="is_read",
            field=models.BooleanField(
                default=False,
                help_text="True when this notification has been read in the eve client",
            ),
        ),
    ]
