# Generated by Django 4.0.10 on 2023-09-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memberaudit", "0014_alter_characterrole_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="token_error_notified_at",
            field=models.DateTimeField(
                default=None,
                help_text="Time when user was last notified about a token error.",
                null=True,
            ),
        ),
    ]
