# Generated by Django 4.0.10 on 2023-11-13 14:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("memberaudit", "0015_add_ship_item_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CharacterLocation",
        ),
    ]
