# Generated by Django 4.0.10 on 2023-12-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memberaudit", "0015_charactership_item_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="characterupdatestatus",
            name="parent_task_id",
        ),
        migrations.RemoveField(
            model_name="characterupdatestatus",
            name="root_task_id",
        ),
        migrations.AddField(
            model_name="characterupdatestatus",
            name="update_finished_at",
            field=models.DateTimeField(
                db_index=True,
                default=None,
                help_text="Finish time of an actual update",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="characterupdatestatus",
            name="update_started_at",
            field=models.DateTimeField(
                db_index=True,
                default=None,
                help_text="Start time of an actual update",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="characterupdatestatus",
            name="finished_at",
            field=models.DateTimeField(
                db_index=True,
                default=None,
                help_text="Finish time of an update attempt",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="characterupdatestatus",
            name="started_at",
            field=models.DateTimeField(
                db_index=True,
                default=None,
                help_text="Start time of an update attempt",
                null=True,
            ),
        ),
    ]
