# Generated by Django 4.0.10 on 2023-12-03 16:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("memberaudit", "0015_charactership_item_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="characterupdatestatus",
            name="parent_task_id",
        ),
        migrations.RemoveField(
            model_name="characterupdatestatus",
            name="root_task_id",
        ),
    ]
