# Generated by Django 4.0.10 on 2023-12-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memberaudit", "0016_remove_characterupdatestatus_parent_task_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterupdatestatus",
            name="update_finished_at",
            field=models.DateTimeField(
                db_index=True,
                default=None,
                help_text="Finish time of an actual update",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="characterupdatestatus",
            name="update_started_at",
            field=models.DateTimeField(
                db_index=True,
                default=None,
                help_text="Start time of an actual update",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="characterupdatestatus",
            name="finished_at",
            field=models.DateTimeField(
                db_index=True,
                default=None,
                help_text="Finish time of an update attempt",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="characterupdatestatus",
            name="started_at",
            field=models.DateTimeField(
                db_index=True,
                default=None,
                help_text="Start time of an update attempt",
                null=True,
            ),
        ),
    ]
