# Generated by Django 4.0.10 on 2023-12-08 22:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("memberaudit", "0016_remove_characterupdatestatus_parent_task_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="characterupdatestatus",
            old_name="finished_at",
            new_name="run_finished_at",
        ),
        migrations.RenameField(
            model_name="characterupdatestatus",
            old_name="started_at",
            new_name="run_started_at",
        ),
    ]
