# Generated by Django 4.0.10 on 2023-12-08 23:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "memberaudit",
            "0017_rename_finished_at_characterupdatestatus_run_finished_at_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="characterupdatestatus",
            old_name="last_error_message",
            new_name="error_message",
        ),
    ]
