# Generated by Django 5.2.16 on 2026-07-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberaudit", "0020_add_new_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="shared_at",
            field=models.DateTimeField(
                default=None,
                help_text="Time when this character was last shared.",
                null=True,
            ),
        ),
    ]
